/**
 * @file 配置中心假数据
 * @description Configuration center mock data
 */

/**
 * 配置中心列表数据
 * Configuration center list item
 */
interface ConfigCenterListItem {
	/** 配置项ID Config item ID */
	configId: string;
	/** 配置项名称 Config item name */
	configName: string;
	/** 配置类型 Config type */
	configType: string;
	/** 配置键名 Config key */
	configKey: string;
	/** 配置值 Config value */
	configValue: string;
	/** 默认值 Default value */
	defaultValue: string;
	/** 配置描述 Config description */
	configDescription: string;
	/** 状态 Status */
	status: string;
	/** 排序号 Sort order */
	sortOrder: number;
	/** 备注 Remark */
	remark: string;
	/** 创建时间 Create time */
	createTime: string;
	/** 更新时间 Update time */
	updateTime: string;
	/** 创建人 Creator */
	creator: string;
	/** 更新人 Updater */
	updater: string;
}

/**
 * 配置中心假数据
 * Configuration center mock data
 */
export const mockConfigCenterData: ConfigCenterListItem[] = [
	{
		configId: "CF001",
		configName: "系统名称",
		configType: "系统配置",
		configKey: "system.name",
		configValue: "智慧社区管理系统",
		defaultValue: "智慧社区管理系统",
		configDescription: "系统显示名称，用于页面标题和系统标识",
		status: "启用",
		sortOrder: 1,
		remark: "系统核心配置，不建议修改",
		createTime: "2024-01-01 09:00:00",
		updateTime: "2024-01-15 14:30:00",
		creator: "系统管理员",
		updater: "张伟",
	},
	{
		configId: "CF002",
		configName: "系统版本",
		configType: "系统配置",
		configKey: "system.version",
		configValue: "v2.1.0",
		defaultValue: "v1.0.0",
		configDescription: "系统当前版本号",
		status: "启用",
		sortOrder: 2,
		remark: "版本信息由系统自动更新",
		createTime: "2024-01-01 09:05:00",
		updateTime: "2024-01-20 10:15:00",
		creator: "系统管理员",
		updater: "李娜",
	},
	{
		configId: "CF003",
		configName: "数据库连接池大小",
		configType: "数据库配置",
		configKey: "database.pool.size",
		configValue: "20",
		defaultValue: "10",
		configDescription: "数据库连接池最大连接数",
		status: "启用",
		sortOrder: 101,
		remark: "根据服务器性能调整连接数",
		createTime: "2024-01-01 09:10:00",
		updateTime: "2024-01-25 16:45:00",
		creator: "系统管理员",
		updater: "王强",
	},
	{
		configId: "CF004",
		configName: "缓存过期时间",
		configType: "缓存配置",
		configKey: "cache.expire.time",
		configValue: "3600",
		defaultValue: "1800",
		configDescription: "Redis缓存过期时间（秒）",
		status: "启用",
		sortOrder: 201,
		remark: "根据业务需求调整缓存时间",
		createTime: "2024-01-01 09:15:00",
		updateTime: "2024-01-18 11:20:00",
		creator: "系统管理员",
		updater: "刘芳",
	},
	{
		configId: "CF005",
		configName: "JWT密钥",
		configType: "安全配置",
		configKey: "security.jwt.secret",
		configValue: "MySecretKey123456789",
		defaultValue: "defaultSecret",
		configDescription: "JWT令牌签名密钥",
		status: "启用",
		sortOrder: 301,
		remark: "请定期更换密钥确保安全性",
		createTime: "2024-01-01 09:20:00",
		updateTime: "2024-01-22 13:30:00",
		creator: "系统管理员",
		updater: "陈明",
	},
	{
		configId: "CF006",
		configName: "文件上传大小限制",
		configType: "文件配置",
		configKey: "file.upload.max.size",
		configValue: "10485760",
		defaultValue: "5242880",
		configDescription: "文件上传大小限制（字节）",
		status: "启用",
		sortOrder: 401,
		remark: "限制为10MB，可根据需求调整",
		createTime: "2024-01-01 09:25:00",
		updateTime: "2024-01-19 15:00:00",
		creator: "系统管理员",
		updater: "赵华",
	},
	{
		configId: "CF007",
		configName: "邮件服务器地址",
		configType: "邮件配置",
		configKey: "mail.smtp.host",
		configValue: "smtp.example.com",
		defaultValue: "localhost",
		configDescription: "SMTP邮件服务器地址",
		status: "启用",
		sortOrder: 501,
		remark: "配置外部邮件服务器地址",
		createTime: "2024-01-01 09:30:00",
		updateTime: "2024-01-21 12:45:00",
		creator: "系统管理员",
		updater: "孙丽",
	},
	{
		configId: "CF008",
		configName: "接口超时时间",
		configType: "接口配置",
		configKey: "api.timeout",
		configValue: "30000",
		defaultValue: "10000",
		configDescription: "API接口请求超时时间（毫秒）",
		status: "启用",
		sortOrder: 601,
		remark: "网络环境较慢时可适当延长",
		createTime: "2024-01-01 09:35:00",
		updateTime: "2024-01-23 14:15:00",
		creator: "系统管理员",
		updater: "周涛",
	},
	{
		configId: "CF009",
		configName: "系统维护模式",
		configType: "系统配置",
		configKey: "system.maintenance.mode",
		configValue: "false",
		defaultValue: "false",
		configDescription: "系统维护模式开关",
		status: "启用",
		sortOrder: 3,
		remark: "维护时系统将暂停服务",
		createTime: "2024-01-01 09:40:00",
		updateTime: "2024-01-24 16:20:00",
		creator: "系统管理员",
		updater: "吴敏",
	},
	{
		configId: "CF010",
		configName: "日志级别",
		configType: "系统配置",
		configKey: "system.log.level",
		configValue: "INFO",
		defaultValue: "DEBUG",
		configDescription: "系统日志记录级别",
		status: "启用",
		sortOrder: 4,
		remark: "生产环境建议使用INFO级别",
		createTime: "2024-01-01 09:45:00",
		updateTime: "2024-01-26 10:30:00",
		creator: "系统管理员",
		updater: "郑洁",
	},
	{
		configId: "CF011",
		configName: "分页大小",
		configType: "业务配置",
		configKey: "business.page.size",
		configValue: "20",
		defaultValue: "10",
		configDescription: "列表分页默认大小",
		status: "启用",
		sortOrder: 701,
		remark: "影响数据列表显示效率",
		createTime: "2024-01-01 09:50:00",
		updateTime: "2024-01-27 11:40:00",
		creator: "系统管理员",
		updater: "黄峰",
	},
	{
		configId: "CF012",
		configName: "密码最小长度",
		configType: "安全配置",
		configKey: "security.password.min.length",
		configValue: "8",
		defaultValue: "6",
		configDescription: "用户密码最小长度要求",
		status: "启用",
		sortOrder: 302,
		remark: "提高密码复杂度要求",
		createTime: "2024-01-01 09:55:00",
		updateTime: "2024-01-28 15:25:00",
		creator: "系统管理员",
		updater: "杨柳",
	},
	{
		configId: "CF013",
		configName: "会话超时时间",
		configType: "安全配置",
		configKey: "security.session.timeout",
		configValue: "7200",
		defaultValue: "3600",
		configDescription: "用户会话超时时间（秒）",
		status: "启用",
		sortOrder: 303,
		remark: "2小时后自动退出登录",
		createTime: "2024-01-01 10:00:00",
		updateTime: "2024-01-29 13:50:00",
		creator: "系统管理员",
		updater: "徐磊",
	},
	{
		configId: "CF014",
		configName: "文件存储路径",
		configType: "文件配置",
		configKey: "file.storage.path",
		configValue: "/data/uploads",
		defaultValue: "/tmp/uploads",
		configDescription: "文件上传存储路径",
		status: "启用",
		sortOrder: 402,
		remark: "确保目录有足够的磁盘空间",
		createTime: "2024-01-01 10:05:00",
		updateTime: "2024-01-30 09:35:00",
		creator: "系统管理员",
		updater: "朱婷",
	},
	{
		configId: "CF015",
		configName: "邮件端口",
		configType: "邮件配置",
		configKey: "mail.smtp.port",
		configValue: "587",
		defaultValue: "25",
		configDescription: "SMTP邮件服务器端口",
		status: "启用",
		sortOrder: 502,
		remark: "使用TLS加密端口587",
		createTime: "2024-01-01 10:10:00",
		updateTime: "2024-02-01 14:10:00",
		creator: "系统管理员",
		updater: "高峰",
	},
	{
		configId: "CF016",
		configName: "数据库连接超时",
		configType: "数据库配置",
		configKey: "database.connection.timeout",
		configValue: "30",
		defaultValue: "10",
		configDescription: "数据库连接超时时间（秒）",
		status: "启用",
		sortOrder: 102,
		remark: "网络环境较差时可适当延长",
		createTime: "2024-01-01 10:15:00",
		updateTime: "2024-02-02 16:55:00",
		creator: "系统管理员",
		updater: "林琳",
	},
	{
		configId: "CF017",
		configName: "缓存最大内存",
		configType: "缓存配置",
		configKey: "cache.max.memory",
		configValue: "1024",
		defaultValue: "512",
		configDescription: "缓存最大内存使用量（MB）",
		status: "启用",
		sortOrder: 202,
		remark: "根据服务器内存配置调整",
		createTime: "2024-01-01 10:20:00",
		updateTime: "2024-02-03 12:20:00",
		creator: "系统管理员",
		updater: "马超",
	},
	{
		configId: "CF018",
		configName: "API访问频率限制",
		configType: "接口配置",
		configKey: "api.rate.limit",
		configValue: "1000",
		defaultValue: "500",
		configDescription: "每分钟API访问次数限制",
		status: "启用",
		sortOrder: 602,
		remark: "防止API滥用和攻击",
		createTime: "2024-01-01 10:25:00",
		updateTime: "2024-02-04 15:40:00",
		creator: "系统管理员",
		updater: "韩雪",
	},
	{
		configId: "CF019",
		configName: "系统主题",
		configType: "业务配置",
		configKey: "business.system.theme",
		configValue: "light",
		defaultValue: "light",
		configDescription: "系统默认主题风格",
		status: "启用",
		sortOrder: 702,
		remark: "支持light和dark主题",
		createTime: "2024-01-01 10:30:00",
		updateTime: "2024-02-05 10:15:00",
		creator: "系统管理员",
		updater: "邓伟",
	},
	{
		configId: "CF020",
		configName: "备份保留天数",
		configType: "系统配置",
		configKey: "system.backup.retention.days",
		configValue: "30",
		defaultValue: "7",
		configDescription: "系统备份文件保留天数",
		status: "启用",
		sortOrder: 5,
		remark: "定期清理过期备份文件",
		createTime: "2024-01-01 10:35:00",
		updateTime: "2024-02-06 13:25:00",
		creator: "系统管理员",
		updater: "曹阳",
	},
	{
		configId: "CF021",
		configName: "邮件发送者",
		configType: "邮件配置",
		configKey: "mail.from.address",
		configValue: "noreply@smartcommunity.com",
		defaultValue: "admin@example.com",
		configDescription: "系统邮件发送者地址",
		status: "启用",
		sortOrder: 503,
		remark: "系统通知邮件的发送地址",
		createTime: "2024-01-01 10:40:00",
		updateTime: "2024-02-07 11:50:00",
		creator: "系统管理员",
		updater: "彭丽",
	},
	{
		configId: "CF022",
		configName: "文件允许类型",
		configType: "文件配置",
		configKey: "file.allowed.types",
		configValue: "jpg,png,pdf,doc,docx",
		defaultValue: "jpg,png",
		configDescription: "允许上传的文件类型",
		status: "启用",
		sortOrder: 403,
		remark: "根据业务需求添加文件类型",
		createTime: "2024-01-01 10:45:00",
		updateTime: "2024-02-08 14:35:00",
		creator: "系统管理员",
		updater: "袁浩",
	},
	{
		configId: "CF023",
		configName: "数据库名称",
		configType: "数据库配置",
		configKey: "database.name",
		configValue: "smart_community_db",
		defaultValue: "test_db",
		configDescription: "系统数据库名称",
		status: "启用",
		sortOrder: 103,
		remark: "生产环境数据库名称",
		createTime: "2024-01-01 10:50:00",
		updateTime: "2024-02-09 16:10:00",
		creator: "系统管理员",
		updater: "田静",
	},
	{
		configId: "CF024",
		configName: "缓存键前缀",
		configType: "缓存配置",
		configKey: "cache.key.prefix",
		configValue: "sc:",
		defaultValue: "app:",
		configDescription: "缓存键名前缀",
		status: "启用",
		sortOrder: 203,
		remark: "避免缓存键冲突",
		createTime: "2024-01-01 10:55:00",
		updateTime: "2024-02-10 09:45:00",
		creator: "系统管理员",
		updater: "史强",
	},
	{
		configId: "CF025",
		configName: "密码复杂度要求",
		configType: "安全配置",
		configKey: "security.password.complexity",
		configValue: "true",
		defaultValue: "false",
		configDescription: "是否启用密码复杂度检查",
		status: "启用",
		sortOrder: 304,
		remark: "提高账户安全性",
		createTime: "2024-01-01 11:00:00",
		updateTime: "2024-02-11 12:05:00",
		creator: "系统管理员",
		updater: "段娜",
	},
	{
		configId: "CF026",
		configName: "接口重试次数",
		configType: "接口配置",
		configKey: "api.retry.count",
		configValue: "3",
		defaultValue: "1",
		configDescription: "API调用失败重试次数",
		status: "启用",
		sortOrder: 603,
		remark: "提高接口调用成功率",
		createTime: "2024-01-01 11:05:00",
		updateTime: "2024-02-12 15:20:00",
		creator: "系统管理员",
		updater: "雷军",
	},
	{
		configId: "CF027",
		configName: "系统时区",
		configType: "系统配置",
		configKey: "system.timezone",
		configValue: "Asia/Shanghai",
		defaultValue: "UTC",
		configDescription: "系统默认时区",
		status: "启用",
		sortOrder: 6,
		remark: "影响所有时间相关功能",
		createTime: "2024-01-01 11:10:00",
		updateTime: "2024-02-13 10:40:00",
		creator: "系统管理员",
		updater: "贺平",
	},
	{
		configId: "CF028",
		configName: "邮件用户名",
		configType: "邮件配置",
		configKey: "mail.username",
		configValue: "system@smartcommunity.com",
		defaultValue: "admin@example.com",
		configDescription: "邮件服务器登录用户名",
		status: "启用",
		sortOrder: 504,
		remark: "邮件服务器认证用户",
		createTime: "2024-01-01 11:15:00",
		updateTime: "2024-02-14 14:50:00",
		creator: "系统管理员",
		updater: "倪伟",
	},
	{
		configId: "CF029",
		configName: "文件临时目录",
		configType: "文件配置",
		configKey: "file.temp.dir",
		configValue: "/data/temp",
		defaultValue: "/tmp",
		configDescription: "文件临时处理目录",
		status: "启用",
		sortOrder: 404,
		remark: "确保目录权限正确",
		createTime: "2024-01-01 11:20:00",
		updateTime: "2024-02-15 11:15:00",
		creator: "系统管理员",
		updater: "康辉",
	},
	{
		configId: "CF030",
		configName: "数据库字符集",
		configType: "数据库配置",
		configKey: "database.charset",
		configValue: "utf8mb4",
		defaultValue: "utf8",
		configDescription: "数据库连接字符集",
		status: "启用",
		sortOrder: 104,
		remark: "支持完整的UTF-8字符集",
		createTime: "2024-01-01 11:25:00",
		updateTime: "2024-02-16 16:30:00",
		creator: "系统管理员",
		updater: "殷雪梅",
	},
	{
		configId: "CF031",
		configName: "缓存序列化方式",
		configType: "缓存配置",
		configKey: "cache.serialization",
		configValue: "json",
		defaultValue: "string",
		configDescription: "缓存数据序列化方式",
		status: "启用",
		sortOrder: 204,
		remark: "JSON序列化支持复杂数据类型",
		createTime: "2024-01-01 11:30:00",
		updateTime: "2024-02-17 13:45:00",
		creator: "系统管理员",
		updater: "毕福剑",
	},
	{
		configId: "CF032",
		configName: "API文档地址",
		configType: "接口配置",
		configKey: "api.doc.url",
		configValue: "https://api.smartcommunity.com/docs",
		defaultValue: "http://localhost:8080/docs",
		configDescription: "API接口文档访问地址",
		status: "启用",
		sortOrder: 604,
		remark: "开发者文档访问地址",
		createTime: "2024-01-01 11:35:00",
		updateTime: "2024-02-18 09:20:00",
		creator: "系统管理员",
		updater: "章子怡",
	},
	{
		configId: "CF033",
		configName: "系统Logo",
		configType: "业务配置",
		configKey: "business.system.logo",
		configValue: "/assets/logo.png",
		defaultValue: "/assets/default-logo.png",
		configDescription: "系统Logo图片路径",
		status: "启用",
		sortOrder: 703,
		remark: "系统品牌标识",
		createTime: "2024-01-01 11:40:00",
		updateTime: "2024-02-19 15:55:00",
		creator: "系统管理员",
		updater: "郭德纲",
	},
	{
		configId: "CF034",
		configName: "日志保留天数",
		configType: "系统配置",
		configKey: "system.log.retention.days",
		configValue: "90",
		defaultValue: "30",
		configDescription: "系统日志文件保留天数",
		status: "启用",
		sortOrder: 7,
		remark: "定期清理过期日志文件",
		createTime: "2024-01-01 11:45:00",
		updateTime: "2024-02-20 12:30:00",
		creator: "系统管理员",
		updater: "赵薇",
	},
	{
		configId: "CF035",
		configName: "邮件模板目录",
		configType: "邮件配置",
		configKey: "mail.template.dir",
		configValue: "/templates/email",
		defaultValue: "/templates",
		configDescription: "邮件模板文件存储目录",
		status: "禁用",
		sortOrder: 505,
		remark: "暂时禁用，等待模板完善",
		createTime: "2024-01-01 11:50:00",
		updateTime: "2024-02-21 10:50:00",
		creator: "系统管理员",
		updater: "范冰冰",
	},
];
